### ISSUE TITLE
Remove wallet button not visible but clickable

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-ui#130]
## Description

There is remove wallet button available on wallet details view, but styling make it invisible. In result we cannot see the button, but we can easily interact with it.

```
<button type="button" data-testid="remove-wallet" class="text-white bg-transparent p-0 border-0 underline appearance-none cursor-pointer grow basis-0 no-underline">
<svg class="inline-block fill-current fill-transparent w-[16px]" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
<path ...
</path></svg></button>
```

![image](https://user-images.githubusercontent.com/24473278/226350064-82bf32bb-a30e-4657-b123-4327d4ff65bd.png)
![image](https://user-images.githubusercontent.com/24473278/226350092-cfd4a936-3f28-44c5-acb4-6b0a7488436f.png)

**Comment by notbot00** [comment]
not sure if this ticket is still relevant, as things changed recently. will close this, @radoslaw-szpiech , please feel free to reopen if it is still an issue, and add some description on how to reproduce it (platform, etc), for me it shows correctly.

![Image](https://user-images.githubusercontent.com/105208209/235429413-a24b1903-1618-448b-99c0-bbab6f20f149.png)
