### ISSUE TITLE
approve and reject buttons hidden on second transaction after approving an initial successful transaction

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-ui#171]
## Description

When attempting to approve a second transaction, the approve and reject buttons are hidden in the wallet ui. I cannot get around this by resizing the browser window either in my automated tests. 

## Steps to Reproduce

1. Checkout test/add-transaction-tests (if branch no longer exists then checkout develop)
2. Go to transaction.test.ts
3. Comment out test.fixme() in the test 'should list multiple transactions'
4. run `yarn nx run wallet-mock:e2e --path transaction.test.ts --grep=multiple* --headed` in the terminal if you want to see the failure
If you want to step through, run the above command with `--debug` on the end.
5. Observe first transaction is clickable, and is approved successfully
6. Observe second transaction does not show the approve/reject buttons. It appears as though the second approve/reject prompt appears behind the nav panel at the bottom of the screen containing the transactions/wallets/settings buttons whereas the initial prompt takes precedence over the nav panel visually.

Here is the difference in display between the first and second prompt:
1st prompt:
![image](https://user-images.githubusercontent.com/37066267/231994268-e609b3d9-91a2-4f29-9146-956750615600.png)

2nd prompt:
![image](https://user-images.githubusercontent.com/37066267/231994363-3347f0e6-ed05-4aa4-b34d-eda8580e2b64.png)

## Expected behavior
Can approve or reject further transactions after successfully approving one.

## Device details

**Desktop (please complete the following information):**

- OS: Windows 11 but using wsl, Ubuntu 22.04.2 LTS distribution
- Browser chromium 111.0.5563.19

**Comment by notbot00** [comment]
cannot reproduce this in the real wallet app environment, assuming it's some faulty test thing? also, cannot seem to run the run the command provided, it fails with `no matches found: --grep=multiple*`
