### ISSUE TITLE
Long urls in connections list collide with button

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-ui#62]
## Description

As per title

## Steps to Reproduce

1. Connect with an app with a long url
2. Open wallet and view connections

## Expected behavior

A different layout or simply text truncation

## Screenshots

![Screenshot 2023-01-09 at 11 14 38](https://user-images.githubusercontent.com/6803987/211390400-eb7bbd7f-e3ee-49d9-84b4-3a5493c32a56.jpg)

**Comment by notbot00** [comment]
they don't collide anymore, the width of the container expands and becomes scrollable. tried to make it that so it uses ellipsis, but it just seems like a lot more hacky to do it that way. anyway, confirmed that the problem is gone.
