### ISSUE TITLE
EPIC: Improve transaction status feedback from wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-ui#74]
## EPIC

As a user 
I want to see what node the transaction was sent to and track it's progress (success/failure) when submitting transactions via the desktop wallet 
So that I can understand the status 

## Recording 

https://user-images.githubusercontent.com/46783148/214906347-9f31385e-af3b-40dd-8d21-28df6fd03e99.mov

## Sketch
From [the Miro board](https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764545848004603&cot=14):

![image](https://user-images.githubusercontent.com/1080322/218743667-d1414b07-6bf4-43b4-843e-ac42e437a76b.png)

## Additional details / background info
- Child tickets:
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/487
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/488
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/489
  - Also relevant - https://github.com/vegaprotocol/vegawallet-desktop/issues/491

**Comment by neildawson** [comment]
On Friday 10th, @notbot00, @ValentinTrinque and I met to review the proposed routes. We agreed to pursue option 2 (toasts) AND option 3 (transaction history view), in addition to changes to the transaction details modal.

I have created tickets for those three tasks. I don't think there are any dependencies, they could be completed in any order.
